### ISSUE TITLE
How to get the original functionality of "L"?

### ISSUE THREAD

**Issue by ian-vu** [ollyhayes/Colemak-Vim#2]
I would like to have the original functionality of "L" which moves cursor to the middle of the screen, while keeping "l" to go to end of word.

Is this possible?

**Comment by ollyhayes** [comment]
It should be possible! To make these changes I just forked the repository, and then did a global search for each key in single quotes e.g. `'i'` or `'I'`, and switched it for the key I wanted it to be.

You can see the exact changes I made by comparing my repository with the original one, and looking at the 'Files changed' tab here: https://github.com/VSCodeVim/Vim/compare/master...ollyhayes:master.

You should be able to follow the same process to use which ever keys you like. How would you enter insert mode if you would use "L" like you're suggesting?

**Comment by ian-vu** [comment]
Thanks for explaining. 

> How would you enter insert mode if you would use "L" like you're suggesting?

I would leave "l" (lowercase) the same, which would allow me to enter insert mode. 

However, I would like the original functionality of "L" (uppercase) which allows me to use Shift + L which moves carret to the bottom of the screen. 

That is ultimately what I am after.

Any suggestions to how to achieve this?

**Comment by ollyhayes** [comment]
Ah okay I see what you mean!

I think the easiest way for you do to this would be to fork this repository, and then change this line back to `['I']` like it is in the original: https://github.com/ollyhayes/Colemak-Vim/blob/master/src/actions/commands/actions.ts#L2575.

```javascript
@RegisterAction
export class CommandInsertAtFirstCharacter extends BaseCommand {
  modes = [Mode.Normal];
  keys = ['I']; // I had changed this to 'L' for colemak-vim
```

Then `'L'` would go to the bottom of the screen, `'l'` would enter insert mode.

**Comment by ian-vu** [comment]
Thanks for the help and suggestion!
