### ISSUE TITLE
evil-colemak bindings

### ISSUE THREAD

**Issue by ehrenschwan-gh** [ollyhayes/Colemak-Vim#3]
I usually use emacs and with that evil and evil-colemak and this package rebinds the key sligthly different then your remappings. But I have to use VSCode for work now so it would be nice if I can use those remaps.

I know vim has a lot to do with muscle memory so I'm not asking to completely redo the mappings but maybe have an option for the different remapping.

Unfortunately I do not now how to develop VSCode-extensions else I would implement it myself and do a pull request. I do now Typescript though so if you don't have the time to do it and can tell me where the remaps happen, I could look a bit into the development of VSCode-extensions and implement it myself.

The rebinds are [here](https://github.com/wbolster/emacs-evil-colemak-basics), but basically I would like the option to remap:
| Mapping | Key |
| ------- | :-: |
| insert | <kbd>u</kbd> |
| undo  | <kbd>l</kbd> |

And then what evil-colemak calls the t-f-j rotation:
| Mapping | Key |
| ------- | :-: |
| jump to character | <kbd>t</kbd> |
| jump to end of word | <kbd>f</kbd> |
| jump until character | <kbd>j</kbd> |

**Comment by ehrenschwan-gh** [comment]
I've looked at the code and also the extension a bit while doing so and there is other functionality missing like the change inside key binds and I think it is easier for me to fork the original repo and add all that functionality myself, so I'm closing this issue.

**Comment by ollyhayes** [comment]
Ah interesting, I hadn't heard of this remapping. I agree though it's easier to fork the original than to base it on this version and make it configurable, the modifications aren't too complicated.

In case you didn't see it I gave a short explanation here of how I did this, maybe you can use the same process: https://github.com/ollyhayes/Colemak-Vim/issues/2#issuecomment-640222035.

Maybe I misunderstood you but the text-object commands should work in this version, at least you can do for example 'vlw' or 'clw' to select or change inner-word (equivalent to 'viw' and 'ciw' in normal vim).

Good luck!

**Comment by ehrenschwan-gh** [comment]
Yes, I missunderstood that, of course the text object commands are then remapped to 'l' too. I found out that the extension now supports remapping out of the box [here](https://gist.github.com/LucaSchwan/693aa984f4cffd9f10530e4bb1dcb428) is my settings.json with all that it took to get it to work.

**Comment by ollyhayes** [comment]
Thanks for posting that, I gave your key bindings a try with the normal vim extension. Are inner text objects commands still using `i` then, even though `i` is now the right-arrow key?

Does that work okay? For example if you want to start a visual selection and then select also the character to the right: `vi`, it'll start a text object command instead.

**Comment by ehrenschwan-gh** [comment]
Insert is binded to `u` and the inside text object is too. That causes the remap for undo to `l`. This made sense when coming from qwerty cause those keys are where `i` & `u` are on qwerty. The remapping in VS Code Vim remaps whole buttons not functionality.
